version: '3.8'
services:
  consumer:
    container_name: ${PROJECT_NAME}_consumer
    hostname: consumer
    restart: unless-stopped
    image: ${PROJECT_NAME}_consumer_image
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
      - emailsender_backend_kafka-net

networks:
  emailsender_backend_kafka-net:
    external: true
